# Site settings
title: Chronobiology Lab @ IZTECH
name: Chronobiology Lab at IZTECH
email: altugdidikoglu@iyte.edu.tr
description: > # this means to ignore newlines until "baseurl:"
  Light Sleep Cognition Health. Research group headed by Assistant Professor Altug Didikoglu in the 
  Izmir Institute of Technology, Urla, Izmir.
baseurl: "" # the subpath of your site, e.g. /blog/
url: https://chronobiology-lab.github.io
last_updated: # leave blank if you don't want to display last updated
#twitter_username: jekyllrb
github_username: chronobiology-lab

# -----------------------------------------------------------------------------
# News
# -----------------------------------------------------------------------------
blog_name: Chronobiology Lab @ IZTECH
blog_description: Light Sleep Cognition Health

# Pagination
paginate: 4
permalink: /news/:year/:title/
paginate_path: "news/page:num"

text:
  pagination:
    newer: 'Newer'
    older: 'Older'


# Optional features
show_social_icons:  false
enable_anchorjs:    false
enable_katex:       true


# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------
collections:
  news:
    defaults:
      layout: post
    output: true
    permalink: /updates/:path/
  projects:
    output: true
    permalink: /projects/:path/
  pastsem:
    output: true
    permalink: /pastsem/:path/

news_limit: 5


# Build settings
markdown: kramdown
highlighter: rouge

# Includes & excludes
include: ['_pages']
exclude: [vendor]

# Plug-ins
plugins:
    - jekyll-email-protect
    - jekyll-paginate
    - jemoji
    - jekyll-sitemap


# -----------------------------------------------------------------------------
# Other settings
# -----------------------------------------------------------------------------
jquery_version: "1.12.4"
katex_version: "0.9.0"
anchorjs_version: "3.2.2"
